name: Anthropic Watchdog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *' # 日本時間 朝5:00

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run collector
        run: python collect_anthropic.py

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          git commit -m "Auto update Anthropic data" || exit 0
          git push
